function create_simple_presentation()
    % Create a simple PowerPoint presentation of the HRS analysis results
    
    try
        % Create PowerPoint application
        ppt = actxserver('PowerPoint.Application');
        ppt.Visible = 1;
        
        % Create new presentation
        presentation = ppt.Presentations.Add;
        
        % Slide 1: Title Slide
        slide1 = presentation.Slides.Add(1, 1);
        slide1.Shapes.Title.TextFrame.TextRange.Text = 'HRS Parameter Analysis Results';
        
        % Slide 2: Problem Statement
        slide2 = presentation.Slides.Add(2, 2);
        slide2.Shapes.Title.TextFrame.TextRange.Text = 'Problem Statement';
        slide2.Shapes.Item(2).TextFrame.TextRange.Text = ['• Initial observation: Many identical values across experiments' char(10)...
               '• Question: Are parameter variations working correctly?' char(10)...
               '• Investigation: Compare same study across different experiments' char(10)...
               '• Focus: First 4 experiments with varying WashOutUpper parameters' char(10)...
               '• Expected: Different parameter values should produce different results'];
        
        % Slide 3: Experiment Parameters
        slide3 = presentation.Slides.Add(3, 2);
        slide3.Shapes.Title.TextFrame.TextRange.Text = 'Experiment Parameters';
        slide3.Shapes.Item(2).TextFrame.TextRange.Text = ['Parameter Variations (ADC parameters identical):' char(10) char(10)...
               'Exp001: WU=4.0,    PZ=850/1050/1200' char(10)...
               'Exp002: WU=2.5,    PZ=850/1050/1200' char(10)...
               'Exp003: WU=3.0,    PZ=850/1050/1200' char(10)...
               'Exp004: WU=3.5,    PZ=850/1050/1200' char(10) char(10)...
               'Expected Impact:' char(10)...
               '• WashOutUpper → DCE masks → HRS masks → All features except ADC_Prostate_Mean' char(10)...
               '• ADC PZ thresholds → ADC-based features (ADC_HRS1_Mean, ADC_HRS6_Mean)'];
        
        % Slide 4: Analysis Results
        slide4 = presentation.Slides.Add(4, 2);
        slide4.Shapes.Title.TextFrame.TextRange.Text = 'Analysis Results Overview';
        slide4.Shapes.Item(2).TextFrame.TextRange.Text = ['✅ ADC_Prostate_Mean: 100% identical (EXPECTED - not affected by parameters)' char(10) char(10)...
               '✅ HRS1_Volume: 68-94% identical (GOOD - shows variation)' char(10)...
               '✅ HRS6_Volume: 62-92% identical (GOOD - shows variation)' char(10)...
               '✅ HRS7_6_Ratio: 60-91% identical (GOOD - shows variation)' char(10)...
               '✅ ADC_HRS1_Mean: 57-88% identical (GOOD - shows variation)' char(10)...
               '✅ ADC_HRS6_Mean: 51-81% identical (GOOD - shows variation)' char(10) char(10)...
               'Conclusion: Parameter variations ARE working correctly!'];
        
        % Slide 5: Root Cause Analysis
        slide5 = presentation.Slides.Add(5, 2);
        slide5.Shapes.Title.TextFrame.TextRange.Text = 'Root Cause Analysis';
        slide5.Shapes.Item(2).TextFrame.TextRange.Text = ['Debugging Process:' char(10) char(10)...
               '1. Reviewed HRS Java code implementation' char(10)...
               '2. Traced DCEScore calculation' char(10)...
               '3. Analyzed patient MAST007 as example' char(10) char(10)...
               'Key Finding: DCEScore calculation explains similarities' char(10) char(10)...
               'DCEScore = (Math.max(Math.min(DCEFeatureSum, upper), lower) - lower) / (upper - lower)' char(10) char(10)...
               'When DCEFeatureSum values are similar, DCEScore becomes identical, leading to identical HRS features.'];
        
        % Slide 6: MAST007 Debug Example
        slide6 = presentation.Slides.Add(6, 2);
        slide6.Shapes.Title.TextFrame.TextRange.Text = 'MAST007 Debug Example';
        slide6.Shapes.Item(2).TextFrame.TextRange.Text = ['Patient MAST007 Analysis:' char(10) char(10)...
               'WashOut = 4.0:  DCEFeatureSum = 6.536  → DCEScore = 1.0' char(10)...
               'WashOut = 2.5:  DCEFeatureSum = 3.26   → DCEScore = 1.0' char(10)...
               'WashOut = 3.0:  DCEFeatureSum = 3.26   → DCEScore = 1.0' char(10)...
               'WashOut = 3.5:  DCEFeatureSum = 3.26   → DCEScore = 0.9227' char(10) char(10)...
               'Result: Experiments 1,2,3 identical, Experiment 4 different' char(10) char(10)...
               'This explains why some patients show identical values across experiments 1-3 but differ in experiment 4.'];
        
        % Slide 7: Conclusions
        slide7 = presentation.Slides.Add(7, 2);
        slide7.Shapes.Title.TextFrame.TextRange.Text = 'Conclusions';
        slide7.Shapes.Item(2).TextFrame.TextRange.Text = ['✅ Parameter variations are working correctly' char(10) char(10)...
               '✅ Identical values are explained by DCEScore calculation' char(10) char(10)...
               '✅ Some patients naturally have similar DCEFeatureSum values' char(10) char(10)...
               '✅ When DCEFeatureSum is similar, DCEScore becomes identical' char(10) char(10)...
               '✅ This leads to identical HRS features for those patients' char(10) char(10)...
               '✅ ADC_Prostate_Mean correctly shows no variation (not parameter-dependent)' char(10) char(10)...
               '✅ The system is functioning as designed'];
        
        % Slide 8: Recommendations
        slide8 = presentation.Slides.Add(8, 2);
        slide8.Shapes.Title.TextFrame.TextRange.Text = 'Recommendations';
        slide8.Shapes.Item(2).TextFrame.TextRange.Text = ['For Future Analysis:' char(10) char(10)...
               '1. Document expected behavior: Some patients will have identical values' char(10) char(10)...
               '2. Focus on patients showing variation to assess parameter sensitivity' char(10) char(10)...
               '3. Consider DCEScore thresholds when designing experiments' char(10) char(10)...
               '4. Validate parameter ranges to ensure meaningful variation' char(10) char(10)...
               '5. Monitor ADC_Prostate_Mean separately (parameter-independent feature)' char(10) char(10)...
               '6. Use statistical analysis to identify parameter-sensitive patient subgroups'];
        
        % Save presentation
        savePath = 'C:\Users\tamer\Desktop\Mast Cases TTest experiments\CODE\HRS_Analysis_Results.pptx';
        presentation.SaveAs(savePath);
        
        fprintf('Presentation saved to: %s\n', savePath);
        fprintf('Total slides created: %d\n', presentation.Slides.Count);
        
        % Close presentation
        presentation.Close;
        ppt.Quit;
        
        fprintf('PowerPoint presentation created successfully!\n');
        
    catch ME
        fprintf('Error creating presentation: %s\n', ME.message);
        if exist('presentation', 'var')
            presentation.Close;
        end
        if exist('ppt', 'var')
            ppt.Quit;
        end
    end
end
