function create_analysis_presentation()
    % Create a comprehensive PowerPoint presentation of the HRS analysis results
    
    % Create PowerPoint application
    ppt = actxserver('PowerPoint.Application');
    ppt.Visible = 1;
    
    % Create new presentation
    presentation = ppt.Presentations.Add;
    
    % Slide 1: Title Slide
    slide1 = presentation.Slides.Add(1, 1); % ppLayoutTitle
    slide1.Shapes.Title.TextFrame.TextRange.Text = 'HRS Parameter Analysis Results';
    if slide1.Shapes.Count > 1
        slide1.Shapes.Item(2).TextFrame.TextRange.Text = 'Investigation of Identical Values Across Experiments';
        slide1.Shapes.Item(2).TextFrame.TextRange.Font.Size = 18;
    end
    
    % Slide 2: Problem Statement
    slide2 = presentation.Slides.Add(2, 2); % ppLayoutText
    slide2.Shapes.Title.TextFrame.TextRange.Text = 'Problem Statement';
    content = ['• Initial observation: Many identical values across experiments' newline...
               '• Question: Are parameter variations working correctly?' newline...
               '• Investigation: Compare same study across different experiments' newline...
               '• Focus: First 4 experiments with varying WashOutUpper parameters' newline...
               '• Expected: Different parameter values should produce different results'];
    slide2.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 3: Experiment Parameters
    slide3 = presentation.Slides.Add(3, 2); % ppLayoutText
    slide3.Shapes.Title.TextFrame.TextRange.Text = 'Experiment Parameters';
    content = ['Parameter Variations (ADC parameters identical):' newline newline...
               'Exp001: WU=4.0,    PZ=850/1050/1200' newline...
               'Exp002: WU=2.5,    PZ=850/1050/1200' newline...
               'Exp003: WU=3.0,    PZ=850/1050/1200' newline...
               'Exp004: WU=3.5,    PZ=850/1050/1200' newline newline...
               'Expected Impact:' newline...
               '• WashOutUpper → DCE masks → HRS masks → All features except ADC_Prostate_Mean' newline...
               '• ADC PZ thresholds → ADC-based features (ADC_HRS1_Mean, ADC_HRS6_Mean)'];
    slide3.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 4: Analysis Results Overview
    slide4 = presentation.Slides.Add(4, 2); % ppLayoutText
    slide4.Shapes.Title.TextFrame.TextRange.Text = 'Analysis Results Overview';
    content = ['✅ ADC_Prostate_Mean: 100% identical (EXPECTED - not affected by parameters)' newline newline...
               '✅ HRS1_Volume: 68-94% identical (GOOD - shows variation)' newline...
               '✅ HRS6_Volume: 62-92% identical (GOOD - shows variation)' newline...
               '✅ HRS7_6_Ratio: 60-91% identical (GOOD - shows variation)' newline...
               '✅ ADC_HRS1_Mean: 57-88% identical (GOOD - shows variation)' newline...
               '✅ ADC_HRS6_Mean: 51-81% identical (GOOD - shows variation)' newline newline...
               'Conclusion: Parameter variations ARE working correctly!'];
    slide4.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 5: Root Cause Analysis
    slide5 = presentation.Slides.Add(5, 2); % ppLayoutText
    slide5.Shapes.Title.TextFrame.TextRange.Text = 'Root Cause Analysis';
    content = ['Debugging Process:' newline newline...
               '1. Reviewed HRS Java code implementation' newline...
               '2. Traced DCEScore calculation' newline...
               '3. Analyzed patient MAST007 as example' newline newline...
               'Key Finding: DCEScore calculation explains similarities' newline newline...
               'DCEScore = (Math.max(Math.min(DCEFeatureSum, upper), lower) - lower) / (upper - lower)' newline newline...
               'When DCEFeatureSum values are similar, DCEScore becomes identical, leading to identical HRS features.'];
    slide5.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 6: MAST007 Debug Example
    slide6 = presentation.Slides.Add(6, 2); % ppLayoutText
    slide6.Shapes.Title.TextFrame.TextRange.Text = 'MAST007 Debug Example';
    content = ['Patient MAST007 Analysis:' newline newline...
               'WashOut = 4.0:  DCEFeatureSum = 6.536  → DCEScore = 1.0' newline...
               'WashOut = 2.5:  DCEFeatureSum = 3.26   → DCEScore = 1.0' newline...
               'WashOut = 3.0:  DCEFeatureSum = 3.26   → DCEScore = 1.0' newline...
               'WashOut = 3.5:  DCEFeatureSum = 3.26   → DCEScore = 0.9227' newline newline...
               'Result: Experiments 1,2,3 identical, Experiment 4 different' newline newline...
               'This explains why some patients show identical values across experiments 1-3 but differ in experiment 4.'];
    slide6.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 7: Technical Implementation
    slide7 = presentation.Slides.Add(7, 2); % ppLayoutText
    slide7.Shapes.Title.TextFrame.TextRange.Text = 'Technical Implementation';
    content = ['HRS Algorithm Flow:' newline newline...
               '1. DCE Processing:' newline...
               '   • Calculate DCEFeatureSum from DCE data' newline...
               '   • Apply WashOutUpper threshold' newline...
               '   • Compute DCEScore = (max(min(DCEFeatureSum, upper), lower) - lower) / (upper - lower)' newline newline...
               '2. HRS Calculation:' newline...
               '   • wNorm = min(wWP.get(i, 0) / wNthPercentile, 1)' newline...
               '   • hrsDCE.set(i, 0, wNorm * DCEScore)' newline newline...
               '3. Feature Extraction:' newline...
               '   • HRS volumes calculated from final HRS masks' newline...
               '   • ADC means calculated within HRS regions' newline...
               '   • Ratios computed from volume relationships'];
    slide7.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 8: Parameter Impact Summary
    slide8 = presentation.Slides.Add(8, 2); % ppLayoutText
    slide8.Shapes.Title.TextFrame.TextRange.Text = 'Parameter Impact Summary';
    content = ['Parameter Effects on Features:' newline newline...
               'WashOutUpper Parameter:' newline...
               '• Affects: HRS1_Volume, HRS6_Volume, HRS7_6_Ratio, ADC_HRS1_Mean, ADC_HRS6_Mean' newline...
               '• Mechanism: DCE mask → HRS mask → Feature calculation' newline...
               '• Result: Some patients identical across experiments 1-3, different in experiment 4' newline newline...
               'ADC PZ Thresholds:' newline...
               '• Affects: ADC_HRS1_Mean, ADC_HRS6_Mean' newline...
               '• Mechanism: Direct ADC value calculation within HRS regions' newline...
               '• Result: Additional variation in ADC-based features' newline newline...
               'ADC_Prostate_Mean:' newline...
               '• Not affected by any parameters (expected behavior)'];
    slide8.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 9: Conclusions
    slide9 = presentation.Slides.Add(9, 2); % ppLayoutText
    slide9.Shapes.Title.TextFrame.TextRange.Text = 'Conclusions';
    content = ['✅ Parameter variations are working correctly' newline newline...
               '✅ Identical values are explained by DCEScore calculation' newline newline...
               '✅ Some patients naturally have similar DCEFeatureSum values' newline newline...
               '✅ When DCEFeatureSum is similar, DCEScore becomes identical' newline newline...
               '✅ This leads to identical HRS features for those patients' newline newline...
               '✅ ADC_Prostate_Mean correctly shows no variation (not parameter-dependent)' newline newline...
               '✅ The system is functioning as designed'];
    slide9.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Slide 10: Recommendations
    slide10 = presentation.Slides.Add(10, 2); % ppLayoutText
    slide10.Shapes.Title.TextFrame.TextRange.Text = 'Recommendations';
    content = ['For Future Analysis:' newline newline...
               '1. Document expected behavior: Some patients will have identical values' newline newline...
               '2. Focus on patients showing variation to assess parameter sensitivity' newline newline...
               '3. Consider DCEScore thresholds when designing experiments' newline newline...
               '4. Validate parameter ranges to ensure meaningful variation' newline newline...
               '5. Monitor ADC_Prostate_Mean separately (parameter-independent feature)' newline newline...
               '6. Use statistical analysis to identify parameter-sensitive patient subgroups'];
    slide10.Shapes.Item(2).TextFrame.TextRange.Text = content;
    
    % Save presentation
    savePath = 'C:\Users\tamer\Desktop\Mast Cases TTest experiments\CODE\HRS_Analysis_Results.pptx';
    presentation.SaveAs(savePath);
    
    fprintf('Presentation saved to: %s\n', savePath);
    fprintf('Total slides created: %d\n', presentation.Slides.Count);
    
    % Close presentation
    presentation.Close;
    ppt.Quit;
    
    fprintf('PowerPoint presentation created successfully!\n');
end
